JAVAOPT=

all:
	javac $(JAVAOPT) Z2Forwarder.java
	javac $(JAVAOPT) Z2Packet.java
	javac $(JAVAOPT) Z2Receiver.java
	javac $(JAVAOPT) Z2Sender.java
	javac $(JAVAOPT) TimedPacket.java

clean:
	rm -f *.class
	rm -f *.log